site_name: EDD - Design Urbano
site_url: https://projetoDesignEDD.com/

theme:
  name: material
  palette:
    primary: orange
    secondary: red
  # logo:
  # favicon:

plugins:
  - search

nav:
    - Home: index.md
    - Atividades:
      - Deriva: deriva.md
    - About: about.md