name: gh-deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: MkDocs GithubPages Automatic deployment CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      -run: pip install mkdocs-material
      -run: mkdocs gh-deploy --force